[package]
name = "alloc-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
arrayvec = { version = "0.7.4", default-features = false }

[dev-dependencies]
rand = "0.8.5"
